web/config/routes.rb
Rails.application.routes.draw do
  
  post 'parkings/disabled'
  resources :parkings
  resources :favorites
  resources :rentals

  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :omniauth_authorize => 'users/omniauth_authorize' }
  
  get 'home/contact'
  get 'home/about'
  get 'home/account'
  post 'home/mailcontact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  
  root 'home#index'
  

end

web/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @district = District.all
  end
  
  def about
  end
  
  def contact
    
  end
  
  def account
    if !current_user
      redirect_to root_path
    else
      @parking = Parking.find_by_sql("SELECT * FROM parkings WHERE users_id = #{current_user.id} AND estado!=0 ")
      @favorite = Favorite.find_by_sql("SELECT p.*, f.id as favorite_id FROM parkings p JOIN favorites f ON f.parkings_id = p.id WHERE p.estado!= 0 AND f.users_id= #{current_user.id}")
      
      @rentals = Rental.find_by_sql("SELECT p.*, r.id AS rentals_id FROM parkings p RIGHT JOIN rentals r ON r.parkings_id = p.id WHERE r.estado = 1 AND r.users_id = #{current_user.id}")

      @monto = Rental.find_by_sql("SELECT SUM(r.monto) AS monto_total FROM rentals r LEFT JOIN parkings p ON r.parkings_id = p.id WHERE p.users_id = #{current_user.id}")
      
    end
  end
  
  def mailcontact
    # Send mailer
    UserMailer.contact_mail.deliver()
  end
  
end

web/app/views/home/account.html.erb
<div class="container-fluid">
  <div class="row" id="div-account">
    <div class="col-md-3">
      <div>
        <a href="#" class="thumbnail">
          <%= image_tag("profiles/user1_profile.jpg", :alt => "rss feed") %>
        </a>
      </div>
      <div class="list-group">
        <a href="javascript:;" data-id="account-profile">
          Total Alquilado: <%= @monto[0].monto_total %>
        </a>
        <a href="javascript:;" data-id="account-profile" class="list-group-item active">
          MIS DATOS 
        </a>
        <a href="javascript:;" data-id="account-reserves" class="list-group-item">
          <span class="badge" id="rentals-cant"><%= @rentals.size %></span>
          MIS ALQUILERES
        </a>
        <a href="javascript:;" data-id="account-parkings" class="list-group-item ">
          <span class="badge" id="parking-cant"><%= @parking.size %></span>
          MIS PARQUEOS
        </a>
        <a href="javascript:;" data-id="account-favorites" class="list-group-item">
          <span class="badge" id="favorite-cant"><%= @favorite.size %></span>
          MIS FAVORITOS
        </a>
      </div>
    </div>
    <div class="col-md-9">
      <div class="panel panel-primary " id="account-profile">
        <div class="panel-heading text-center"><strong>Actuaizar mis datos</strong></div>
        <div class="panel-body">
          
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Nombres y Apellidos:</label>
                  <div><%= current_user.nombre %></div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Correo:</label>
                  <div><%= current_user.email %></div>
                </div>
              </div>
            </div>
            
            <a class="btn btn-success" href="<%= edit_user_registration_path %>"><i class="fa fa-pencil"></i> Editar</a>
        </div>
      </div>
      <div class="panel panel-primary hidden" id="account-reserves">
        <div class="panel-heading text-center"><strong>LISTA DE ALQUILERES REALIZADOS</strong></div>
        <div class="panel-body">
          <table class="table table-bordered">
            <tr>
              <th class='col-md-2'>Título</th>
              <th class='col-md-5'>Descripción</th>
              <th class='col-md-3'>Dirección</th>
              <th class='col-md-2'></th>
            </tr>
            <% @rentals.each do |rentals| %>
              <tr>
                <td><%= rentals.titulo %></td>
                <td><%= truncate(rentals.descripcion, :length => 100) %></td>
                <td><%= truncate(rentals.direccion, :length => 100) %></td>
                <td class="text-center">
                  <a href="<%= parkings_path %>/<%= rentals.id %>" class="btn btn-warning ">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                  </a>
                  <button type="button" data-id="<%= rentals.rentals_id %>" class="btn btn-danger btn-delete-rentals">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  </button>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
      <div class="panel panel-primary hidden" id="account-parkings">
        <div class="panel-heading text-center"><strong>LISTA DE PARQUEOS REGISTRADOS</strong></div>
        <div class="panel-body">
          <button type="button" class="btn btn-success" id="btn-new-parking">
            <i class="fa fa-plus" aria-hidden="true"></i> Nuevo Parqueo
          </button>
          <br> <br>
          <table class="table table-bordered">
            <tr>
              <th class='col-md-2'>Título</th>
              <th class='col-md-5'>Descripción</th>
              <th class='col-md-1'>CostoxDía</th>
              <th class='col-md-1'>CostoxMes</th>
              <th class='col-md-1'>CostoxAño</th>
              <th class='col-md-2'></th>
            </tr>
            <% 
            if @parking
              @parking.each do |park| %>
                <% 
                if park.estado == 2
                  clase = "success"
                elsif park.estado == 3
                  clase = "warning"
                end %>
                <tr class="<%= clase %>">
                  <td><%= park.titulo %> </td>
                  <td><%= truncate(park.descripcion, :length => 100) %></td>
                  <td><%= park.costo_dia %></td>
                  <td><%= park.costo_mes %></td>
                  <td><%= park.costo_anho %></td>
                  <td class="text-center">
                    <button type="button" data-id="<%= park.id %>" class="btn btn-warning btn-disable-parking">
                      <i class="fa fa-ban" aria-hidden="true"></i>
                    </button>
                    &nbsp;
                    <button type="button" data-id="<%= park.id %>" class="btn btn-primary btn-edit-parking">
                      <i class="fa fa-pencil" aria-hidden="true"></i>
                    </button>
                    &nbsp;
                    <button type="button" data-id="<%= park.id %>" class="btn btn-danger btn-delete-parking">
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                  </td>
                </tr> 
              <% end
            end %>
          </table>
        </div>
      </div>
      <div class="panel panel-primary hidden" id="account-favorites">
        <div class="panel-heading text-center"><strong>LISTA DE PARQUEOS FAVORITOS</strong></div>
        <div class="panel-body">

          <table class="table table-bordered">
            <tr>
              <th class='col-md-2'>Título</th>
              <th class='col-md-5'>Descripción</th>
              <th class='col-md-3'>Dirección</th>
              <th class='col-md-2'></th>
            </tr>
            <% @favorite.each do |favorite| %>
              <tr>
                <td><%= favorite.titulo %></td>
                <td><%= truncate(favorite.descripcion, :length => 100) %></td>
                <td><%= truncate(favorite.direccion, :length => 100) %></td>
                <td class="text-center">
                  <button type="button" data-id="<%= favorite.favorite_id %>" class="btn btn-danger btn-delete-favorite">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  </button>
                </td>
              </tr> 
            <%end%>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :javascript do %>
<%= javascript_include_tag 'account' %>
<% end %>

web/app/views/home/contact.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-10 col-sm-offset-1 '>
      <div class="panel panel-primary">
        <div class="panel-heading">
          Contáctenos
        </div>
        <div class="panel-body">
          <div class="row">
            <div id="div-mapa" style="height:350px" class="col-md-7">
              
            </div>
            
            <div class="col-md-5">
              <%= form_tag home_mailcontact_path, method: :post do %>
                <div class="form-group">
                  <%= label_tag 'nombres' %>
                  <%= text_field_tag 'nombres', params[:nombres], class: 'form-control', placeholder:'Nombres y Apellidos' %>
                </div>
                
                <div class="form-group">
                  <%= label_tag 'teléfono' %>
                  <%= text_field_tag 'telefono', params[:telefono], class: 'form-control', placeholder: 'Teléfono' %>
                </div>
                <div class="form-group">
                  <%= label_tag 'mensaje' %>
                  <%= text_area_tag 'mensaje', params[:mensaje], class: 'form-control', placeholder: 'Mensaje' %>
                </div>
                  
                <div class="form-group">
                  <%= button_tag 'Enviar', class: 'btn btn-primary form-control' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :javascript do %>
<%= javascript_include_tag 'contact' %>
<% end %>

web/app/views/home/index.html.erb
<% content_for :stylesheets do %>
<%= stylesheet_link_tag 'home' %>
<% end %>


<div class="hero">
  <h1>TuParqueo.com en:</h1>
  <form class="form-inline" method="GET" action="/parkings">
    <div class="form-group">
      <input type="text" name="direccion" class="form-control" placeholder ="Direccion" />
    </div>
    <div class="form-group">
        <input type="date" name="fecha_inicio"  value="" class="form-control" placeholder ="fecha_inicio" />
      </div>
    
    <div class="form-group">
      <select class="form-control" name="distrito">
        <option value="0">:: Todos ::</option>
        <% @district.each do |district| %>
          <option value="<%= district.id %>">
            <%= district.nombre %>
          </option>
        <% end %>
      </select>
    </div>
    
    <div class="form-group">
      <button class="btn btn-success">Buscar</button>
    </div>
  </form>
  <br>
  </br>
</div>


<div class="container" id="list-thumbnail">
  <div class="row text-center">
    <div class="col-md-3">
      <a href="#">
        <%= image_tag 'informacion-servicio' , :class=> 'img-responsive' %>
        <div class="caption">
          <h3>Información del servicio</h3>
        </div>                
       </a>
    </div>
            
    <div class="col-md-3">
      <a href="#">
        <%= image_tag 'terminos-y-condiciones' , :class=> 'img-responsive'%>
        <h3>Términos y condiciones de uso</h3>
       </a>
    </div>
    
    <div class="col-md-3">'
      <a href="/home/testimonio">
        <%= image_tag 'testimonios' , :class=> 'img-responsive'%>
        <h3>Testimonios</h3>
     </a>
    </div>  
    <div class="col-md-3">
      <a href="#">
        <%= image_tag 'preguntas-y-respuestas' , :class=> 'img-responsive'%>
        <h3>Preguntas y respuestas frecuentes</h3>
       </a>
    </div>            
  </div>
</div>