web/config/routes.rb
Rails.application.routes.draw do
  
  post 'parkings/disabled'
  resources :parkings
  resources :favorites
  resources :rentals

  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :omniauth_authorize => 'users/omniauth_authorize' }
  
  get 'home/contact'
  get 'home/about'
  get 'home/account'
  post 'home/mailcontact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  
  root 'home#index'
  

end

web/app/models/parking.rb
class Parking < ApplicationRecord
    has_attached_file :image, styles: {big: '600x400>', large: '288x216>', medium: '200x200>', thumb: '48x48>' }
    do_not_validate_attachment_file_type :image
end

web/app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
    def index
        @district = District.all
        # @parking = Parking.find_by(districts_id: params[:distrito])
        if params[:distrito].empty? == false && params[:distrito] !='0'
            #@parking = Parking.find_by_sql("SELECT p.*, f.id as favorite_id FROM parkings p LEFT JOIN favorites f ON f.parkings_id = p.id WHERE p.estado = 1 AND p.direccion LIKE '%#{params[:direccion]}%' AND p.districts_id = #{params[:distrito]}")
            @parking = Parking.find_by_sql("SELECT p.*, f.id as favorite_id, u.nombre as usuario_name FROM parkings p LEFT JOIN favorites f ON f.parkings_id = p.id AND f.users_id = #{current_user.id} LEFT JOIN rentals r ON r.parkings_id = p.id LEFT JOIN users u ON u.id=p.users_id WHERE (p.estado = 1 OR p.estado = 2)  AND p.direccion LIKE '%#{params[:direccion]}%' AND p.districts_id = #{params[:distrito]} AND (r.fecha_fin IS NULL OR r.fecha_fin < '#{params[:fecha_inicio]}' )")
            @district_search = District.find_by(id: params[:distrito])
        else
            #@parking = Parking.find_by_sql("SELECT p.*, f.id as favorite_id FROM parkings p LEFT JOIN favorites f ON f.parkings_id = p.id WHERE p.estado = 1 AND p.direccion LIKE '%#{params[:direccion]}%'")
            @parking = Parking.find_by_sql("SELECT p.*, f.id as favorite_id, u.nombre as usuario_name FROM parkings p LEFT JOIN favorites f ON f.parkings_id = p.id AND f.users_id = #{current_user.id} LEFT JOIN rentals r ON r.parkings_id = p.id LEFT JOIN users u ON u.id=p.users_id WHERE (p.estado = 1 OR p.estado = 2) AND p.direccion LIKE '%#{params[:direccion]}%'  AND (r.fecha_fin IS NULL OR r.fecha_fin < '#{params[:fecha_inicio]}')")
            @district_search = District.first
        end
    end
    #select p.*, f.id as favorite_id, r.fecha_inicio, r.fecha_fin FROM parkings p LEFT JOIN favorites f ON f.parkings_id = p.id LEFT JOIN rentals r ON r.parkings_id = p.id  WHERE p.estado = 1 AND ( r.fecha_fin < '2016-08-28' OR r.fecha_fin IS NULL)
    def disabled 
        parking = Parking.find_by(id: params[:id])
        if parking.estado == 1
            parking.update(estado: 3)
        elsif parking.estado == 3
            parking.update(estado: 1)
        end
    end
    
    def show
        @parking = Parking.find(params[:id])
        @rental = Rental.new
    end
    
    def new
        @parking = Parking.new
        @district = District.all
        render '_form_parking', layout: 'blank'
    end
    
    def edit
        @parking = Parking.find(params[:id])
        @district = District.all
        render '_form_parking', layout: 'blank'
    end
    
    def update
        @parking = Parking.find(params[:id])
        if @parking.update_attributes(parking_params)
            redirect_to home_account_path
        else
            render action: 'edit'
        end
    end
    
    def destroy
        parking = Parking.find_by(id: params[:id])
        parking.update(estado: 0)
        # Parking.find(params[:id]).destroy
    end
    
    def create
        @parking = Parking.new(parking_params)
        @parking.users_id = current_user.id
        @parking.estado = 1
        if @parking.save
            redirect_to home_account_path
        else
            render action: 'new'
        end
    end
    
    private
    def parking_params
        params.require(:parking).permit(:titulo, :descripcion, :costo_dia, :costo_mes, :costo_anho, :latitud, :longitud, :direccion, :districts_id, :terminos_condiciones, :image, :file_name,:image_file_name)
    end
    
end

web/app/views/parkings/_form_parking.html.erb
<%= form_for @parking do |f| %>
  <div class="form-group">
    <%= f.label :titulo, 'Título:', :class =>'control-form' %>
    <%= f.text_field :titulo, :class =>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :disctrict_id, 'Distrito', :class => 'control-form' %>
    
    <%= f.select(:districts_id,[],{}, { :class => "form-control"} ) do %>
      <% @district.each do |district| %>
        <%= content_tag(:option, district.nombre, value: district.id) %>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :image, 'Imagen:', :class => 'control-form' %>
    <%= f.file_field :image, :class => 'form-control' %>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :costo_dia, 'Costo por día:' %>
        <%= f.text_field :costo_dia, :class => 'form-control' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :costo_mes, 'Costo por mes:' %>
        <%= f.text_field :costo_mes, :class => 'form-control' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :costo_anho, 'Costo por año:' %>
        <%= f.text_field :costo_anho, :class => 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descripcion, 'Descripción: ', :class =>'control-form' %>
    <%= f.text_area :descripcion, :class =>'form-control', :rows =>4 %>  
  </div>
  <div class="form-group">
    <%= f.label :terminos_condiciones, 'Términos y condiciones: ', :class =>'control-form' %>
    <%= f.text_area :terminos_condiciones, :class =>'form-control', :rows =>4 %>  
  </div>
  <div class="form-group">
    <%= f.label :direccion, 'Dirección: ', :class =>'control-form' %>
    <%= f.text_field :direccion, :class => 'form-control', :readonly => true %>
    <div id="mapa-direccion" style="width:100%; height:300px;"></div>
    <%= f.text_field :latitud, :class => 'hidden' %>
    <%= f.text_field :longitud, :class => 'hidden' %>
  </div>
  
  
  <div class="form-group">
    <%= f.submit 'Guardar', :class =>'form-control btn btn-success' %>
  </div>
<% end %>

<script type="text/javascript">
  var cliente, geocoder;
  
  var initialize = function(){
    var latInit = ($.trim($('#parking_latitud').val()))?$.trim($('#parking_latitud').val()):-12.081792;
    var lonInit = ($.trim($('#parking_longitud').val()))?$.trim($('#parking_longitud').val()):-77.017936;
    geocoder = new google.maps.Geocoder();
    var mapOptions = {
        zoom : 14,
        center: new google.maps.LatLng(latInit, lonInit)
    }
    var map = new google.maps.Map(document.getElementById('mapa-direccion'), mapOptions);
    if($.trim($('#parking_latitud').val())){
      console.log(latInit, lonInit);
      var latLng = new google.maps.LatLng(latInit, lonInit);
      cliente = new google.maps.Marker({
            position: latLng,
            map: map,
            title: 'Punto de Origen',
            // icon: icono,
            draggable: true
        });
    }
    
    
    

    google.maps.event.addListener(map, "click", function (event) {
        latOrigen = event.latLng.lat();
        lonOrigen = event.latLng.lng();
        var latLng = new google.maps.LatLng(latOrigen, lonOrigen);
        if(cliente)
          cliente.setMap(null);
        
        // var icono = '../img/cliente.png';

        obtenerDireccion(latOrigen, lonOrigen);
        $("#parking_latitud").val(latOrigen);
        $("#parking_longitud").val(lonOrigen);
        
        cliente = new google.maps.Marker({
            position: latLng,
            map: map,
            title: 'Punto de Origen',
            // icon: icono,
            draggable: true
        });

        google.maps.event.addListener(cliente, "dragend", function (event) {
            latOrigen = event.latLng.lat();
            lonOrigen = event.latLng.lng();
            obtenerDireccion(latOrigen, lonOrigen);
            $("#parking_latitud").val(latOrigen);
            $("#parking_longitud").val(lonOrigen);
        });
    });
  }
  
  var obtenerDireccion = function (lat, lon) {
    var latLng = new google.maps.LatLng(lat, lon);
    geocoder.geocode({'latLng': latLng}, function (results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
            if (results[0]) {
                var address = results[0].formatted_address;
                console.log(address, '1');
                if (address.indexOf(',') != -1) {
                    var add = address.split(',');
                    address = add[0];
                }
                $("#parking_direccion").val(address);
            }
        } else {
            console.log("No se pudo obtener la dirección");
        }
    });
    
  }
  
  $(document).ready(function() {
    // Inicia Google maps
    
    setTimeout(function() {
    initialize();
      
    }, 2000);
      
  });
</script>

web/app/views/parkings/index.html.erb
<% content_for :stylesheets do %>
<%= stylesheet_link_tag 'parkings' %>
<% end %>
<div class="container-fluid">
  <div class="navbar-search text-center">
    <form class="form-inline" method="GET" action="/parkings">
      <div class="form-group">
        <input type="text" name="direccion" value="<%= params[:direccion] %>" class="form-control" placeholder ="Direccion" />
      </div>
      <div class="form-group">
        <input type="date" name="fecha_inicio"  value="<%= params[:fecha_inicio] %>" class="form-control" placeholder ="fecha_inicio" />
      </div>
      
      <div class="form-group">
        <select class="form-control" name="distrito">
          <option value="0">:: Todos ::</option>
          <% @district.each do |district| %>
            <% if district.id == params[:distrito] %>
              <option value="<%= district.id %>" selected>
                <%= district.nombre %>
              </option>
            <% else %>
              <option value="<%= district.id %>">
                <%= district.nombre %>
              </option>
            <% end %>
          <% end %>
        </select>
      </div>
      
      <div class="form-group">
        <button class="btn btn-success">Buscar</button>
      </div>
    </form>
  </div>
  
  
  <input type="hidden" id="lat_centro" value="<%= @district_search.lat_centro %>" />
  <input type="hidden" id="lon_centro" value="<%= @district_search.lon_centro %>"/>
  <input type="hidden" id="district_id" value="<%= params[:distrito] %>"/>
  
  
  
  <div class="row">
    <div class="col-sm-7" style="height:550px" id="div-mapa">
      
    </div>
    <div class="col-sm-5" id="list-search">
      <%
      if @parking 
        @parking.each do |park| %>
          <div class="row col-principal">    
            <div class="col-sm-5">
              <div class="content-params-parkings">
                <i data-favorite-id="<%= park.favorite_id %>" class="fa <% if park.favorite_id  %>fa-heart <% else %> fa-heart-o<% end %> icon-favorite" data-id="<%= park.id %>" aria-hidden="true"></i>
              </div>
              <a href="<%= parking_path( park.id ) %>">
                <%  if park.image_file_name %>
                  <%= image_tag park.image.url(:large), :class => 'img-responsive' %>
                <% else %>
                  <%= image_tag 'parqueo1.jpg' , :class => 'img-responsive' %>
                <% end %>
              </a>
            </div>
            <a href="<%= parking_path( park.id ) %>">
              <div class="col-sm-7 text-justify">
              <div>
                <label><strong>Título:</strong></label>
                <span class="titulo"><%= park.titulo %></span>
              </div>
              <div>
                <label><strong>Dirección:</strong></label>
                <span class="direccion"><%= park.direccion %></span>
              </div>
              <div>
                <label><strong>Usuario:</strong></label>
                <span class= "titulo"><%= park.usuario_name %></span>
              </div>
              <div>
                <label for=""><strong>Descripción:</strong></label>
                <span> <%= truncate( park.descripcion, :length =>100 ) %> </span>
              </div>
              <div class="row">
                <div class="col-sm-4 text-center">
                  <strong>Día </strong>
                  <p>
                    S/. <%= park.costo_dia %>
                  </p>
                </div>
                <div class="col-sm-4 text-center">
                  <strong>Mes </strong>
                  <p>
                    S/. <%= park.costo_mes %>
                  </p>
                </div>
                <div class="col-sm-4 text-center">
                  <strong>Año </strong>
                  <p>
                    S/. <%= park.costo_anho %>
                  </p>
                </div>
              </div>
            </div>
            </a>
            <input type="hidden" class="latitud" value="<%= park.latitud %>" />
            <input type="hidden" class="longitud" value="<%= park.longitud %>"/>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>  
<% content_for :javascript do %>
<%= javascript_include_tag 'list_parkings' %>
<% end %>

web/app/views/parkings/show.html.erb
<% content_for :stylesheets do %>
<%= stylesheet_link_tag 'detail_parking' %>
<% end %>
<div class="container">
  
  
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="text-center">
        <h3><%= @parking.titulo %></h3>
      </div>
      <div>
        <i class="fa fa-map-marker" aria-hidden="true"></i> 
        <strong>
          <i>
            Dirección: <%= @parking.direccion %>
          </i>
        </strong>
      </div>
    </div>
  	<div class="panel-body">
  	  
  	  <div class="row">
  	    
  	    <!-- IZQUIERDA -->
  	    <div class="col-md-8">
  	      <h4>Descripción:</h4>
  	      <div>
  	        <%= @parking.descripcion %>
  	      </div>
  	      <br>
  	      <br>
  	      <h4>Términos de Renta:</h4>
  	      <div>
  	        <%= @parking.terminos_condiciones %>
  	      </div>
  	    </div>
  	    
  	    <!-- DERECHA -->
  	    <% if current_user.id != @parking.users_id %>
  	      <div class="col-md-4">
  	      <div class="panel panel-primary">
  	        <div class="panel-heading">
  	          Alquiler
  	        </div>
  	        <div class="panel-body">
  	          <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#tab-reserva-dias" aria-controls="tab-reserva-dias" role="tab" data-toggle="tab">Días</a></li>
                  <li role="presentation"><a href="#tab-reserva-meses" aria-controls="tab-reserva-meses" role="tab" data-toggle="tab">Meses</a></li>
                  <li role="presentation"><a href="#tab-reserva-anhos" aria-controls="tab-reserva-anhos" role="tab" data-toggle="tab">Años</a></li>
                </ul>
              
                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane fade in active" id="tab-reserva-dias">
                    <form id="payment-form" method="POST" action="<%= rentals_path %>">
                      <input type="hidden" value="<%= @parking.id %>" id="parkings_id" name="parkings_id" />
                      <div class="form-group">
                        <h4>
                          Precio: S/. <span id="costoDia"><%= @parking.costo_dia %></span>
                        </h4>
                      </div>
                      <hr />
                      <input type="hidden" class="tiempo" name="tiempo" value="dias" />
                      <div class="form-group">
                        <label class="control-label">Fecha Inicio</label>
                        <input type="date" id="fechaInicio" name="fechaInicio" class="form-control" />
                      </div>
                      
                      <div class="form-group">
                        <label class="control-label">Cantidad dias</label>
                        <input type="number" class="form-control" name="cantDias" id="cantDias">
                      </div>
                      
                      <div class="form-group">
                        <label class="control-label">Fecha Fin</label>
                        <br>
                        <input id="fechaFin" type="text" readonly name="fechaFin" class="form-control" />
                      </div>
                      
                      <div class="form-group">
                        <label class="control-label">Monto a Pagar:</label>
                        <br>
                        S./ <input id="montoTotal" readonly name="montoTotal" class="form-control" value="0" />
                      </div>
                      <div class="form-group">
                        <button type="button" class="btn btn-success form-control btn-alquilar">Alquilar</button>
                        
                        <script
                          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="pk_test_om9JIRPO6EFk5cpxkWjHt16G"
                          data-amount="PAGAR"
                          data-name="TuParqueo.com"
                          data-description="Widget"
                          data-image="/img/documentation/checkout/marketplace.png"
                          data-locale="auto">
                        </script>
                      </div>
                    </form>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="tab-reserva-meses">
                    <form>
                      <div class="form-group">
                        <h4>
                          Precio: S/. <%= @parking.costo_mes %>
                        </h4>
                      </div>
                      <hr />
                      <input type="hidden" class="tiempo" value="meses" />
                      <div class="form-group">
                        <label class="control-label">Fecha Inicio</label>
                        <input type="date" class="form-control" />
                      </div>
                      <div class="form-group">
                        <label class="control-label">Fecha Fin</label>
                        <input type="date" class="form-control" />
                      </div>
                      <div class="form-group">
                        <button type="button" class="btn btn-success form-control btn-alquilar">Reservar</button>
                      </div>
                    </form>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="tab-reserva-anhos">
                    <form>
                      <div class="form-group">
                        <h4>
                          Precio: S/. <%= @parking.costo_anho %>
                        </h4>
                      </div>
                      <hr />
                      <input type="hidden" class="tiempo" value="anhos" />
                      <div class="form-group">
                        <label class="control-label">Fecha Inicio</label>
                        <input type="date" class="form-control" />
                      </div>
                      <div class="form-group">
                        <label class="control-label">Fecha Fin</label>
                        <input type="date" class="form-control" />
                      </div>
                      <div class="form-group">
                        <button type="button" class="btn btn-success form-control btn-alquilar">Alquilar</button>
                      </div>
                    </form>
  	   
                  </div>
                </div>
              
              </div>
  	        </div>
  	      </div>
  	      
  	    </div>
  	    <% end %>
  	     
  	  </div>
  	  
  	  <!-- Espacio para el mapa -->
  	  <br>
  	  <br>
  	  <div class="row">
  	    <input type="hidden" value="<%= @parking.latitud %>" id='latitud' />
  	    <input type="hidden" value="<%= @parking.longitud %>" id='longitud' />
    	  <div id="div-mapa" class="col-md-6" style="height: 400px">
    	  </div>
  	    <div class="col-md-6">
	        <div class="carousel slide article-slide" id="article-photo-carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner cont-slider">
          
              <div class="item active">
                <%  if @parking.image_file_name %>
                  <%= image_tag @parking.image.url(:big), :class => 'img-responsive' %>
                <% else %>
                  <%= image_tag 'parqueo1.jpg' , :class => 'img-responsive' %>
                <% end %>
              </div>
              <div class="item">
                <img alt="" title="" src="http://placehold.it/600x400">
              </div>
              <div class="item">
                <img alt="" title="" src="http://placehold.it/600x400">
              </div>
              <div class="item">
                <img alt="" title="" src="http://placehold.it/600x400">
              </div>
            </div>
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li class="active" data-slide-to="0" data-target="#article-photo-carousel">
                <img alt="" src="http://placehold.it/250x180">
              </li>
              <li class="" data-slide-to="1" data-target="#article-photo-carousel">
                <img alt="" src="http://placehold.it/250x180">
              </li>
              <li class="" data-slide-to="2" data-target="#article-photo-carousel">
                <img alt="" src="http://placehold.it/250x180">
              </li>
              <li class="" data-slide-to="3" data-target="#article-photo-carousel">
                <img alt="" src="http://placehold.it/250x180">
              </li>
            </ol>
          </div>
	      </div>
  	  </div>
  	</div>
  </div>
</div>

<% content_for :javascript do %>
<%= javascript_include_tag 'detail_parking' %>
<% end %>